version: "3"

services: 
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181



  # docker compose -f docker-compose.yml up -d
  # docker exec -it kafka /bin/sh
  
  # create topic
  # kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic kafkaprac
  # kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 4 --topic test-topic
  
  # topic list
  # kafka-topics.sh --list --zookeeper zookeeper:2181
  # kafka-topics.sh --list --bootstrap-server localhost:9092
  
  # producer
  # ./kafka-console-producer.sh --broker-list localhost:9092 --topic test-topic


  # producer
  # ./kafka-console-producer.sh --broker-list localhost:9092 --topic test-topic --property "key.separator=-" --property "parse.key=true"

  # consumer
  # ./kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test-topic --from-beginning
  # ./kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test-topic


  # from-beginning, lastest, specific offset
  # __consumer_offsets



  # consumer with key 
  # ./kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test-topic --from-beginning -property "key.separator= - " --property "print.key=true" 

  # ./kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test-topic --group console-consumer-60811




# consumer group
# ./kafka-consumer-groups.sh --bootstrap-server localhost:9092 --list


#  topic describe
#  kafka-topics.sh --describe --topic test-topic --bootstrap-server <kafka-broker>


# https://github.com/dilipsundarraj1/kafka-for-beginners/blob/master/SetUpKafka.md


# root@f7c92c31a8ae:/opt/kafka_2.13-2.8.1/bin# ./zookeeper-shell.sh localhost:2181



# kafka-topics.sh --delete --zookeeper zookeeper:2181 --topic quickstart